// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWJ4NC5MNsPmqSWMA4DAs0f74ARGTtmU',
    appId: '1:304172450545:web:92289e8886bd4d175e9f50',
    messagingSenderId: '304172450545',
    projectId: 'krakflow-rupert-2137',
    authDomain: 'krakflow-rupert-2137.firebaseapp.com',
    storageBucket: 'krakflow-rupert-2137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8JDkABAwRGuTkeApeNW7JTwzP-yLyzG8',
    appId: '1:304172450545:android:a67fc35d1e18ef8f5e9f50',
    messagingSenderId: '304172450545',
    projectId: 'krakflow-rupert-2137',
    storageBucket: 'krakflow-rupert-2137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQNUmyLywuDS_HBD4Le6JHvA6t14gxmI',
    appId: '1:304172450545:ios:f5da5dcf788a1b215e9f50',
    messagingSenderId: '304172450545',
    projectId: 'krakflow-rupert-2137',
    storageBucket: 'krakflow-rupert-2137.firebasestorage.app',
    iosBundleId: 'com.example.krakprojectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQNUmyLywuDS_HBD4Le6JHvA6t14gxmI',
    appId: '1:304172450545:ios:f5da5dcf788a1b215e9f50',
    messagingSenderId: '304172450545',
    projectId: 'krakflow-rupert-2137',
    storageBucket: 'krakflow-rupert-2137.firebasestorage.app',
    iosBundleId: 'com.example.krakprojectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgWJ4NC5MNsPmqSWMA4DAs0f74ARGTtmU',
    appId: '1:304172450545:web:b8ed23d35d08b0765e9f50',
    messagingSenderId: '304172450545',
    projectId: 'krakflow-rupert-2137',
    authDomain: 'krakflow-rupert-2137.firebaseapp.com',
    storageBucket: 'krakflow-rupert-2137.firebasestorage.app',
  );
}
